# This is a basic workflow to help you get started with Actions

name: Build_DS3615_Bootloader

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DS3615_PID: ${{ secrets.DS3615_PID }}
  DS3615_VID: ${{ secrets.DS3615_VID }}
  DS3615_SN: ${{ secrets.DS3615_SN}}
  DS3615_MAC: ${{ secrets.DS3615_MAC}}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: build-docker-image
        run: |
          chmod +x redpill_tool_chain.sh

          sed -i "s/1234XXX123/${DS3615_SN}/g" bromolow_user_config.json
          sed -i "s/XXYYXXYYXXYY/${DS3615_MAC}/g" bromolow_user_config.json
          sed -i "s/0x46f4/${DS3615_VID}/g" bromolow_user_config.json
          sed -i "s/0x0001/${DS3615_PID}/g" bromolow_user_config.json

          ./redpill_tool_chain.sh build bromolow-7.0.1-42214

      - name: generate-bootloader
        run: |
          ./redpill_tool_chain.sh auto bromolow-7.0.1-42214

      - name: upload
        run: |
          sudo mkdir firmware
          sudo mv -f images/*.img firmware/
          curl -sL https://git.io/file-transfer | sh 
          wetrans=$(./transfer wet -s -p 16 --no-progress firmware/)
          wetrans=$(echo $wetrans | grep -o -E "https[^ ]*")
          echo "Download Link:  $wetrans ðŸš€"
          

